/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyBankAtm;

import java.awt.Color;
import static javafx.scene.input.KeyCode.L;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class fastCash extends javax.swing.JFrame {


    public fastCash() {
        initComponents();
       setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(505, 410));
        setPreferredSize(new java.awt.Dimension(510, 430));
        setSize(new java.awt.Dimension(510, 410));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot (61).png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 70);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trans/HOME.jpg"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 70, 30, 30);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trans/BACK.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 70, 30, 30);

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("SELECT AMOUNT");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel21);
        jLabel21.setBounds(170, 110, 170, 21);

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(9, 149, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("SET FAST TRANSACTION");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });
        jPanel1.add(jLabel19);
        jLabel19.setBounds(160, 370, 200, 19);

        L1.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        L1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L1.setText("1000");
        L1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L1MouseExited(evt);
            }
        });
        jPanel1.add(L1);
        L1.setBounds(180, 170, 60, 19);

        L2.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        L2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L2.setText("2000");
        L2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L2MouseExited(evt);
            }
        });
        jPanel1.add(L2);
        L2.setBounds(180, 210, 60, 19);

        L3.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        L3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L3.setText("3000");
        L3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L3MouseExited(evt);
            }
        });
        jPanel1.add(L3);
        L3.setBounds(180, 250, 60, 19);

        L4.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        L4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L4.setText("4000");
        L4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L4MouseExited(evt);
            }
        });
        jPanel1.add(L4);
        L4.setBounds(180, 290, 60, 19);

        L6.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        L6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L6.setText("6000");
        L6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L6MouseExited(evt);
            }
        });
        jPanel1.add(L6);
        L6.setBounds(280, 170, 60, 19);

        L7.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        L7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L7.setText("7000");
        L7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L7MouseExited(evt);
            }
        });
        jPanel1.add(L7);
        L7.setBounds(280, 210, 60, 19);

        L8.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        L8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L8.setText("8000");
        L8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L8MouseExited(evt);
            }
        });
        jPanel1.add(L8);
        L8.setBounds(280, 250, 60, 19);

        L9.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        L9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L9.setText("9000");
        L9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L9MouseExited(evt);
            }
        });
        jPanel1.add(L9);
        L9.setBounds(280, 290, 60, 19);

        L10.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        L10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L10.setText("10000");
        L10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L10MouseExited(evt);
            }
        });
        jPanel1.add(L10);
        L10.setBounds(280, 330, 60, 19);

        L5.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        L5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L5.setText("5000");
        L5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L5MouseExited(evt);
            }
        });
        jPanel1.add(L5);
        L5.setBounds(180, 330, 60, 19);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
      dispose();
        new NewJFrame().setVisible(true);       
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        dispose();
        new mainpage().setVisible(true);       
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
      

    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
      if(L1.isForegroundSet()){
          JOptionPane.showMessageDialog(null,"well done");
      }     
      else{
         JOptionPane.showMessageDialog(null,"try hard"); 
      }
    
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
       
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
      
    }//GEN-LAST:event_jLabel19MouseExited

    private void L1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseClicked
        L1.setOpaque(true);
        L1.setBackground(new Color(110,56,119));
        L1.setForeground(Color.white);
        String s=String.valueOf(1000);
         L2.setBackground(new Color(240,240,240));
        L2.setForeground(Color.black);
         L3.setBackground(new Color(240,240,240));
        L3.setForeground(Color.black);
         L4.setBackground(new Color(240,240,240));
        L4.setForeground(Color.black);
         L5.setBackground(new Color(240,240,240));
        L5.setForeground(Color.black);
         L6.setBackground(new Color(240,240,240));
        L6.setForeground(Color.black);
         L7.setBackground(new Color(240,240,240));
        L7.setForeground(Color.black);
         L8.setBackground(new Color(240,240,240));
        L8.setForeground(Color.black);
         L9.setBackground(new Color(240,240,240));
        L9.setForeground(Color.black);
         L10.setBackground(new Color(240,240,240));
        L10.setForeground(Color.black);
    }//GEN-LAST:event_L1MouseClicked

    private void L1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_L1MouseEntered
 
    private void L1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseExited
        
        L1.setOpaque(true);
        L1.setBackground(new Color(110,56,119));
        L1.setForeground(Color.white);
        String s=String.valueOf(1000);
         L2.setBackground(new Color(240,240,240));
        L2.setForeground(Color.black);
         L3.setBackground(new Color(240,240,240));
        L3.setForeground(Color.black);
         L4.setBackground(new Color(240,240,240));
        L4.setForeground(Color.black);
         L5.setBackground(new Color(240,240,240));
        L5.setForeground(Color.black);
         L6.setBackground(new Color(240,240,240));
        L6.setForeground(Color.black);
         L7.setBackground(new Color(240,240,240));
        L7.setForeground(Color.black);
         L8.setBackground(new Color(240,240,240));
        L8.setForeground(Color.black);
         L9.setBackground(new Color(240,240,240));
        L9.setForeground(Color.black);
         L10.setBackground(new Color(240,240,240));
        L10.setForeground(Color.black);
    }//GEN-LAST:event_L1MouseExited

    private void L2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L2MouseClicked
         L2.setOpaque(true);
        L2.setBackground(new Color(110,56,119));
        L2.setForeground(Color.white);
        String s=String.valueOf(2000);
         L1.setBackground(new Color(240,240,240));
        L1.setForeground(Color.black);
         L3.setBackground(new Color(240,240,240));
        L3.setForeground(Color.black);
         L4.setBackground(new Color(240,240,240));
        L4.setForeground(Color.black);
         L5.setBackground(new Color(240,240,240));
        L5.setForeground(Color.black);
         L6.setBackground(new Color(240,240,240));
        L6.setForeground(Color.black);
         L7.setBackground(new Color(240,240,240));
        L7.setForeground(Color.black);
         L8.setBackground(new Color(240,240,240));
        L8.setForeground(Color.black);
         L9.setBackground(new Color(240,240,240));
        L9.setForeground(Color.black);
         L10.setBackground(new Color(240,240,240));
        L10.setForeground(Color.black);
    }//GEN-LAST:event_L2MouseClicked

    private void L2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_L2MouseEntered

    private void L2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_L2MouseExited

    private void L3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L3MouseClicked
        L3.setOpaque(true);
        L3.setBackground(new Color(110,56,119));
        L3.setForeground(Color.white);
        String s=String.valueOf(3000);
         L1.setBackground(new Color(240,240,240));
        L1.setForeground(Color.black);
         L2.setBackground(new Color(240,240,240));
        L2.setForeground(Color.black);
         L4.setBackground(new Color(240,240,240));
        L4.setForeground(Color.black);
         L5.setBackground(new Color(240,240,240));
        L5.setForeground(Color.black);
         L6.setBackground(new Color(240,240,240));
        L6.setForeground(Color.black);
         L7.setBackground(new Color(240,240,240));
        L7.setForeground(Color.black);
         L8.setBackground(new Color(240,240,240));
        L8.setForeground(Color.black);
         L9.setBackground(new Color(240,240,240));
        L9.setForeground(Color.black);
         L10.setBackground(new Color(240,240,240));
        L10.setForeground(Color.black);
    }//GEN-LAST:event_L3MouseClicked

    private void L3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_L3MouseEntered

    private void L3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_L3MouseExited

    private void L4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L4MouseClicked
       L4.setOpaque(true);
        L4.setBackground(new Color(110,56,119));
        L4.setForeground(Color.white);
        String s=String.valueOf(4000);
         L1.setBackground(new Color(240,240,240));
        L1.setForeground(Color.black);
         L2.setBackground(new Color(240,240,240));
        L2.setForeground(Color.black);
         L3.setBackground(new Color(240,240,240));
        L3.setForeground(Color.black);
         L5.setBackground(new Color(240,240,240));
        L5.setForeground(Color.black);
         L6.setBackground(new Color(240,240,240));
        L6.setForeground(Color.black);
         L7.setBackground(new Color(240,240,240));
        L7.setForeground(Color.black);
         L8.setBackground(new Color(240,240,240));
        L8.setForeground(Color.black);
         L9.setBackground(new Color(240,240,240));
        L9.setForeground(Color.black);
         L10.setBackground(new Color(240,240,240));
        L10.setForeground(Color.black);
        
        
    }//GEN-LAST:event_L4MouseClicked

    private void L4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_L4MouseEntered

    private void L4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_L4MouseExited

    private void L6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L6MouseClicked
      L6.setOpaque(true);
        L6.setBackground(new Color(110,56,119));
        L6.setForeground(Color.white);
        String s=String.valueOf(6000);
         L1.setBackground(new Color(240,240,240));
        L1.setForeground(Color.black);
         L2.setBackground(new Color(240,240,240));
        L2.setForeground(Color.black);
         L3.setBackground(new Color(240,240,240));
        L3.setForeground(Color.black);
         L4.setBackground(new Color(240,240,240));
        L4.setForeground(Color.black);
         L5.setBackground(new Color(240,240,240));
        L5.setForeground(Color.black);
         L7.setBackground(new Color(240,240,240));
        L7.setForeground(Color.black);
         L8.setBackground(new Color(240,240,240));
        L8.setForeground(Color.black);
         L9.setBackground(new Color(240,240,240));
        L9.setForeground(Color.black);
         L10.setBackground(new Color(240,240,240));
        L10.setForeground(Color.black);
    }//GEN-LAST:event_L6MouseClicked

    private void L6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_L6MouseEntered

    private void L6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_L6MouseExited

    private void L7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L7MouseClicked
      L7.setOpaque(true);
        L7.setBackground(new Color(110,56,119));
        L7.setForeground(Color.white);
        String s=String.valueOf(7000);
         L1.setBackground(new Color(240,240,240));
        L1.setForeground(Color.black);
         L2.setBackground(new Color(240,240,240));
        L2.setForeground(Color.black);
         L3.setBackground(new Color(240,240,240));
        L3.setForeground(Color.black);
         L4.setBackground(new Color(240,240,240));
        L4.setForeground(Color.black);
         L5.setBackground(new Color(240,240,240));
        L5.setForeground(Color.black);
         L6.setBackground(new Color(240,240,240));
        L6.setForeground(Color.black);

         L8.setBackground(new Color(240,240,240));
        L8.setForeground(Color.black);
         L9.setBackground(new Color(240,240,240));
        L9.setForeground(Color.black);
         L10.setBackground(new Color(240,240,240));
        L10.setForeground(Color.black);
    }//GEN-LAST:event_L7MouseClicked

    private void L7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_L7MouseEntered

    private void L7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_L7MouseExited

    private void L8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L8MouseClicked
       L8.setOpaque(true);
        L8.setBackground(new Color(110,56,119));
        L8.setForeground(Color.white);
        String s=String.valueOf(8000); L1.setBackground(new Color(240,240,240));
        L1.setForeground(Color.black);
         L2.setBackground(new Color(240,240,240));
        L2.setForeground(Color.black);
         L3.setBackground(new Color(240,240,240));
        L3.setForeground(Color.black);
         L4.setBackground(new Color(240,240,240));
        L4.setForeground(Color.black);
         L5.setBackground(new Color(240,240,240));
        L5.setForeground(Color.black);
         L6.setBackground(new Color(240,240,240));
        L6.setForeground(Color.black);
         L7.setBackground(new Color(240,240,240));
        L7.setForeground(Color.black);
         L9.setBackground(new Color(240,240,240));
        L9.setForeground(Color.black);
         L10.setBackground(new Color(240,240,240));
        L10.setForeground(Color.black);
    }//GEN-LAST:event_L8MouseClicked

    private void L8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_L8MouseEntered

    private void L8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_L8MouseExited

    private void L9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L9MouseClicked
      L9.setOpaque(true);
        L9.setBackground(new Color(110,56,119));
        L9.setForeground(Color.white);
        String s=String.valueOf(9000);
         L1.setBackground(new Color(240,240,240));
        L1.setForeground(Color.black);
         L2.setBackground(new Color(240,240,240));
        L2.setForeground(Color.black);
         L3.setBackground(new Color(240,240,240));
        L3.setForeground(Color.black);
         L4.setBackground(new Color(240,240,240));
        L4.setForeground(Color.black);
         L5.setBackground(new Color(240,240,240));
        L5.setForeground(Color.black);
         L6.setBackground(new Color(240,240,240));
        L6.setForeground(Color.black);
         L7.setBackground(new Color(240,240,240));
        L7.setForeground(Color.black);
         L8.setBackground(new Color(240,240,240));
        L8.setForeground(Color.black);
         L10.setBackground(new Color(240,240,240));
        L10.setForeground(Color.black);
    }//GEN-LAST:event_L9MouseClicked

    private void L9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_L9MouseEntered

    private void L9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_L9MouseExited

    private void L10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L10MouseClicked
        L10.setOpaque(true);
        L10.setBackground(new Color(110,56,119));
        L10.setForeground(Color.white);
        String s=String.valueOf(10000);
         L1.setBackground(new Color(240,240,240));
        L1.setForeground(Color.black);
         L2.setBackground(new Color(240,240,240));
        L2.setForeground(Color.black);
         L3.setBackground(new Color(240,240,240));
        L3.setForeground(Color.black);
         L4.setBackground(new Color(240,240,240));
        L4.setForeground(Color.black);
         L5.setBackground(new Color(240,240,240));
        L5.setForeground(Color.black);
         L6.setBackground(new Color(240,240,240));
        L6.setForeground(Color.black);
         L7.setBackground(new Color(240,240,240));
        L7.setForeground(Color.black);
         L8.setBackground(new Color(240,240,240));
        L8.setForeground(Color.black);
         L9.setBackground(new Color(240,240,240));
        L9.setForeground(Color.black);
    }//GEN-LAST:event_L10MouseClicked

    private void L10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_L10MouseEntered

    private void L10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_L10MouseExited

    private void L5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L5MouseClicked
       L5.setOpaque(true);
        L5.setBackground(new Color(110,56,119));
        L5.setForeground(Color.white);
        String s=String.valueOf(5000);
         L1.setBackground(new Color(240,240,240));
        L1.setForeground(Color.black);
         L2.setBackground(new Color(240,240,240));
        L2.setForeground(Color.black);
         L3.setBackground(new Color(240,240,240));
        L3.setForeground(Color.black);
         L4.setBackground(new Color(240,240,240));
        L4.setForeground(Color.black);
         L6.setBackground(new Color(240,240,240));
        L6.setForeground(Color.black);
         L7.setBackground(new Color(240,240,240));
        L7.setForeground(Color.black);
         L8.setBackground(new Color(240,240,240));
        L8.setForeground(Color.black);
         L9.setBackground(new Color(240,240,240));
        L9.setForeground(Color.black);
         L10.setBackground(new Color(240,240,240));
        L10.setForeground(Color.black);
    }//GEN-LAST:event_L5MouseClicked

    private void L5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_L5MouseEntered

    private void L5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_L5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fastCash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel L9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
